---
title: Lilith Rose Energy
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: 
color_alpha: feeaeb
color_beta: '05009e'
google_analytics: UA—XXXXXXXX-X
instagram_key: 22396560623.1677ed0.c72fe889aab64d009701fc50cfd902fb
instagram_caption: true
description: 
url: 
email: lilithroseenergy@gmail.com
twitter_username: 
default_img: 
social:
  instagram: https://www.instagram.com/lilith_rose_energy/
exclude:
- node_modules
- gulpfile.js
- assets/js/app.js
- README.md
- Gemfile
- Gemfile.lock
markdown: kramdown
permalink: "/:year/:month/:day/:title/"
sass:
  style: compressed
gems:
- jekyll-sitemap
- octopress-autoprefixer
