---
---

---
title: Aquiring.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Personal website
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal
