---
title: Cartwheel
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: ''
color_alpha: feeaeb
color_beta: '05009e'
google_analytics: UA—XXXXXXXX-X
instagram_key: 
instagram_caption: true
description: 
url: ''
email: 
twitter_username: 
default_img: 
social:
  instagram: lilith_rose_energy
exclude:
- node_modules
- gulpfile.js
- assets/js/app.js
- README.md
- Gemfile
- Gemfile.lock
markdown: kramdown
permalink: "/:year/:month/:day/:title/"
sass:
  style: compressed
gems:
- jekyll-sitemap
- octopress-autoprefixer
